server:
  port: 8000

spring:
  application:
    name: gateway

  config:
    import: "optional:consul:"

  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product, /product/**, /product/all
        - id: shopCart
          uri: lb://shopCart
          predicates:
            - Path=/cart, /cart/*, /cart/all, /cart/{cartId}
        - id: user
          uri: lb://user
          predicates:
            - Path=/user,/user/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:1234"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
            allow-credentials: true
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
